### ISSUE TITLE
DXA - XPM - non-mandatory fields

### ISSUE THREAD

**Issue by LjiljanaEric** [sdl/dxa-web-application-dotnet#10]
In the case when component has non-mandatory and empty field, there is no appropriate XPM comment which will indicate that field can be editable by XPM.
This is scenario:
- Schema has mandatory and non-mandatory fields, lets take just text fields as examples.
- Rendering is OK in the case of mandatory field or non-mandatory field which has some text and source of the page is like 
  ![image](https://cloud.githubusercontent.com/assets/1639529/11590970/767bacf0-9a94-11e5-8571-72470e7e3a97.png)
- If the field is non-mandatory and without value, output is different and looks like this
  ![image](https://cloud.githubusercontent.com/assets/1639529/11590973/7ff42618-9a94-11e5-8597-74936ab26810.png)

As it can be noticed there is no XPM comment which will give the information about which field should be editable with XPM. - Code in View used to render non-mandatory fields is
![image](https://cloud.githubusercontent.com/assets/1639529/11590978/8976317c-9a94-11e5-8f7c-7ae5f4a2e194.png)

WebRequestContext.IsPreview is always true for our current development environment so that part is ok. Model.TipText is null in that case, and maybe this is causing the issue.

Problem is related to the output because there is XPM related comment in the source of the page, so XPM does not recognize there is field without value which should be allowed for editing. Without this comment there is no placeholder "<< add text >>" when XPM is active.

Also it is tried with different approach and placing first div as it is on the following image, but same issue is there 
![image](https://cloud.githubusercontent.com/assets/1639529/11590986/997eed84-9a94-11e5-9057-37b2981fe46a.png)

Link to the conversation on StackExchange http://tridion.stackexchange.com/questions/13391/tridion-2013-dxa-xpm-non-mandatory-fields

**Comment by MrSnowflake** [comment]
What's the status of this? Seems to me this is pretty basic behaviour. We allow this already on our current Tridion 2013 XPM implementations.

What's the suggested workaround if there isn't a solution just yet?

**Comment by bkoopman** [comment]
The status of this is that it is an enhancement request, something we will consider for a next release, but no milestone has been set for it yet. Feel free to submit a pull request if you have already implemented it in your own DXA.

**Comment by rpannekoek** [comment]
TSI-1946 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7: `XpmPropertyMetadata` is now also available for fields without values (which makes `@Html.DxaPropertyMarkup` work for such fields).
