### ISSUE TITLE
DXA choose to display description (if available) over title/name field - Hardcoded in code

### ISSUE THREAD

**Issue by vikaskumar185** [sdl/dxa-web-application-dotnet#16]
I see DXA code displaying description field value of a keyword component if it is available and not its name, I know its a best practice though have curiosity to know more.

What I see in the code [here](https://github.com/sdl/dxa-web-application-dotnet/blob/master/Sdl.Web.Tridion/Mapping/DefaultModelBuilder.cs#L690) is that it is hard coded to choose description (if available) over title/name field. 
But as also mentioned as comment in the code:

> // TODO TSI-811: Keyword mapping should also be generic rather than hard-coded like below

`string displayText = String.IsNullOrEmpty(keyword.Description) ? keyword.Title : keyword.Description;`

How and when are we planning to have this ? 

This has also been raised in stack exchange [here](http://tridion.stackexchange.com/questions/13940/where-and-how-do-we-read-keyword-component-fields-name-description-in-dxa).

**Comment by rpannekoek** [comment]
Please use StackExchange for questions and create Issues here for concrete bugs or Enhancement Requests.  Assuming your question is actually an Enhancement Request in disguise: can you explain why the current behavior is not sufficient for you?

**Comment by vikaskumar185** [comment]
HI Rick,

Changed the title to make it more concrete. Indeed it may fall under Enhancement. I dint know where to set that as label to this issue.

**The reason why i raised this is as follow:**
A customer recently raised a request where they wanted to show Title even if they have Description in place in a Keyword component. Because they wanted to use that description to indicate only the company name who had acquired them recently to differentiate between old and new categories.

**Comment by rpannekoek** [comment]
Sounds to me that customer is abusing the Keyword Description for what should have been done in Keyword metadata?  For clarity: we indeed have a story on the DXA backlog to make the Keyword mapping logic more generic and powerful.  It is currently not scoped to a release yet. If people come up with good use cases, we will prioritize the story accordingly, but this doesn't sound like a convincing use case to me...

**Comment by vikaskumar185** [comment]
I completely agree. As i also mentioned in my question, I was more curious to understand whats in pipeline for this and as you said we indeed should look for better use case. Thanks for insights.

**Comment by rpannekoek** [comment]
TSI-811 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7: introduced new class `KeywordModel` which allows access to all CM Keyword properties.
