### ISSUE TITLE
Cannot open Visual Studio solution downloaded from 1.4 source code link

### ISSUE THREAD

**Issue by PhilConil** [sdl/dxa-web-application-dotnet#18]
When downloading the source code via this link:
[https://github.com/sdl/dxa-web-application-dotnet/archive/DXA_1.4_Release.zip](https://github.com/sdl/dxa-web-application-dotnet/archive/DXA_1.4_Release.zip)

The VS solution file cannot be opened (at least on my system).
![dxa sln issue](https://cloud.githubusercontent.com/assets/14806262/14556688/b93395da-02f9-11e6-9221-03a56881a11e.png)

When forking the project, the solution opens nicely.
Hopefully this is only happening on my machine, but wanted to share in case someone can verify and confirm this is an isolated case.
Thanks

**Comment by rpannekoek** [comment]
Did you Unblock the Zip file before unzipping?

**Comment by PhilConil** [comment]
I just tried and it does not help. However I think it is just me because I can actually open the solution from VS directly, just not from Windows Explorer. 
So it's all good, thanks.
