### ISSUE TITLE
format=json doesn't work

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-dotnet#2]
According to the docs, it should be possible to get DXA 1.1 requests in JSON format, however this doesn't work (see http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v2/GUID-C5D23B8A-6846-4187-9997-A9A1010D418E)

The following error shows:

>Self referencing loop detected for property 'Link' with type 'Sdl.Web.Common.Models.Link'. Path 'Regions[0].Entities[0].ItemListElements[0]'.

>Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

>Exception Details: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Link' with type 'Sdl.Web.Common.Models.Link'. Path 'Regions[0].Entities[0].ItemListElements[0]'.

>Source Error: 
>An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

This could be related to this: http://stackoverflow.com/questions/13510204/json-net-self-referencing-loop-detected

**Comment by bkoopman** [comment]
closed by https://github.com/sdl/dxa-web-application-dotnet/commit/a82a44074a12145b81f1e66fc5bc0973a7612de0 in develop branch
