### ISSUE TITLE
Exception occurred Access to the path 'c:\windows\system32\inetsrv\includes.json' is denied.

### ISSUE THREAD

**Issue by ablyth-building-blocks** [sdl/dxa-web-application-dotnet#22]
This appears in my site log files. 

> ERROR - Exception occurred Access to the path 'c:\windows\system32\inetsrv\includes.json' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at DD4T.Factories.BinaryFactory.WriteBinaryToFile(Byte[] bytes, String physicalPath, Dimensions dimensions) in C:\projects\dd4t-core\source\DD4T.Factories\BinaryFactory.cs:line 347

I have narrowed this down to one line of code, which is 

`binaryFactory.TryFindBinary(urlPath, out binary);` in BinaryFileManager 

I think this should actually be

`binaryFactory.TryFindBinary(localFilePath, out binary);`

**Comment by rpannekoek** [comment]
Which version of DD4T are you using? It seems that `DD4T.Factories.BinaryFactory.WriteBinaryToFile` is introduced in DD4T 2.1, whereas DXA 1.5 is still build and tested against DD4T 2.0.

Anyways, the first parameter of `IBinaryFactory.TryFindBinary` is supposed to be an URL path, not a local file path; the local file path is constructed in `DD4T.Factories.BinaryFactory` like this: `Path.Combine(Configuration.BinaryFileSystemCachePath, Path.GetFileName(url))`

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7; refactored `BinaryFileManager` to retrieve Binaries directly from CD API.
