### ISSUE TITLE
Bug in logic for model mapping from embedded schemas with identical sub-field names

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-dotnet#24]
If your source schema has non-unique field names within embedded schemas (for example has two fields which use the same embedded schema, or use embedded schemas which have similarly named fields) then there will be issues with the model mapping (the second property will be mapped from the first embedded schema field, or not be found at all). 

This can be fixed by passing around a context SemanticSchemaField while mapping properties from embedded fields. (see https://github.com/trivident/dxa-web-application-dotnet/commit/f1b7f3bafbe4c900a32be8cdf29b7dda805a2a91)

**Comment by jsuurd** [comment]
Another test case for this issue is when the source schema contains a field with the same name as in the embedded schema (i.e. /link and /paragraph/link). Applying the proposed fix does not seem to address this test case.

**Comment by rpannekoek** [comment]
The DXA 1.6 codebase (e.g. `master` branch) contains a fix that should also cover that case. Can you try?

**Comment by rpannekoek** [comment]
TSI-1758 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.6.
