### ISSUE TITLE
Need a mechanism for passing parameters to Region views

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-dotnet#28]
I have a number of different column views, all of which are pretty much the same container HTML with some additional css classes and data attributes. In an ideal world I would like to create a single N-Column MVC view, and pass parameters to this from the Component Template, much in the way we can pass route values and/or CSS classes via CT metadata to the Entity controller/views.

For now the values I would need to pass are the number of columns (to perform the calculations required for row rendering), and some additional css classes and data attributes to place on the container HTML element.

Adding a specific metadata field for css classes is too specific (not all my attributes are classes), so I think there are the following most generic options:
1. Abuse the existing routeValues metadata field to put region route values in and update the DefaultModelBuilder to pull these into the MvcData of the Region object
2. Add a new regionRouteValues metadata field 

I could then create HtmlHelper methods to pull out appropriate route values in my views. @rpannekoek  - if you prefer one of these, or think of a better way, let me know - I will implement it in a pull request

**Comment by rpannekoek** [comment]
How urgent/important is this Enhancement Request? How bad is it to use several Views (and potentially factor out common code in a shared Partial View?
It seems we're trying to stretch the Region Model based on CT metadata (which is "denormalized") more and more and it's not getting more beautiful...

**Comment by willprice76** [comment]
The first page design we have in already has 6 different column layouts and and I would expect quite some more variations. Irrespective of the CM implementation, Region views are needed in the Web app and the Region mvc data should have a neat mechanism to be able to handle such design variation. If we are waiting for a proper region implementation in CM why not already implement the Web app and have a CT meta based implementation as a best effort for now...

**Comment by rpannekoek** [comment]
TSI-1944 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.6:  Region View and Entity View can access the Page Model through {{WebRequestContext.PageModel}}  (also applies to DXA Java).

**Comment by rpannekoek** [comment]
This is supported in Tridion Sites 9 / DXA 2.1 using *Predefined Regions* and Region metadata.
DXA 2.1 showcases a Multi-column Region View which is parameterized with the number of columns.  The number of columns are stored in CM as Region metadata.
