### ISSUE TITLE
Need support for keyword metadata within view models

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-dotnet#30]
The Tag model only has support for keyword title, description and key. Its a common requirement to have metadata on keywords, which should be available in the derived view models for components using these keywords.

It would be good if subclasses of Tag could be created with SemanticProperty decorators, which would enable the keyword metadata to be mapped to properties in the usual way.

**Comment by ablyth-building-blocks** [comment]
+1

**Comment by rpannekoek** [comment]
TSI-811 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.7: introduced new (base) class `KeywordModel` which can be subclassed.
