### ISSUE TITLE
Missing cd_ambient_conf.xml file

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#33]
When I install create a DXA web application as described in [Setting up a new ASP.NET MVC Web application](http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v6/GUID-B2F30A0E-8BC5-4DDB-B168-B2C7280F5CD8) and start it, the webapp will complain about the "cd_ambient_conf.xml".

```
Failed to load configuration file: C:\Users\me\SourceCode\example-dxa-stite\Site\bin\\config\cd_ambient_conf.xml

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Sdl.Web.Delivery.Core.ConfigurationException: Failed to load configuration file: C:\Users\l19548828\SourceCode\example-dxa-stite\Site\bin\\config\cd_ambient_conf.xml


Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
```

Adding `SDL DXA .NET 1.6\web\web8\web-ref\config\cd_ambient_conf.xml` (from the DXA installation media) to the webapp will resolve the issue. I think this step is missed in the documentation, or in the example web application.

I found this issue on both DXA .NET 1.5 and 1.6, did not test on other versions.

**Comment by rpannekoek** [comment]
Indeed, the step is missing in that topic. It is described here, though: http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v6/GUID-EF63A650-30A9-4DC6-907A-D3FCC742926D

For comments on the docs, please leave a comment on the SDL Documentation Portal.

**Comment by jhorsman** [comment]
Comment is added to [Setting up a new ASP.NET MVC Web application](http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v6/GUID-B2F30A0E-8BC5-4DDB-B168-B2C7280F5CD8)

**Comment by rpannekoek** [comment]
Documentation issue.

**Comment by SnehGour93** [comment]
Facing the same issue
