### ISSUE TITLE
DXA throws error on URL querystring with parameter without value

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#44]
When browsing to a URL with a querystring, with parameter, but without value, a DXA site will raise this error `{"error":"InternalServerError"}`.

URL | result
-----|-------
http://hostname/index.html? | ok
**http://hostname/index.html?parameter** | **error**
http://hostname/index.html?parameter= | ok
http://hostname/index.html?parameter=value | ok

**Comment by jhorsman** [comment]
I have no idea what causes this, the PageController logic seems to be fine.

**Comment by majiccode** [comment]
This issue is caused by the ambient data framework (part of the CIL library).

**Comment by majiccode** [comment]
See internal issue: https://jira.sdl.com/browse/CRQ-6865

**Comment by bkoopman** [comment]
hotfixed on Web 8.5, check with Customer Support for CD_8.5.0.6337

**Comment by jhorsman** [comment]
thanks!
