### ISSUE TITLE
All properties and methods which can thow an NotSupportedException must be marked as obsolete.

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#47]
When using a mocking framework in tests it is really annoying to get those exceptions when the mocking framework just tries to populate the model with test data ;)

To avoid this, make sure to annotate everything that can thow a `NotSupportedException` as `[Obsolete]`.

Maybe it is worth having a script checking for this.

**Comment by jhorsman** [comment]
Fixed on occurence in the PageBase https://github.com/sdl/dxa-web-application-dotnet/pull/46

**Comment by rpannekoek** [comment]
The "problem" is that for some properties, only the setter is obsolete (and throws `NotSupportedException`), but it is not possible to mark only a property setter as obsolete. These setters will be removed in DXA 2.0 as part of deprecated API cleanup.

TSI-878 (Internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 2.0
