### ISSUE TITLE
Localization.EnsureInitialized() should not throw DxaItemNotFoundException

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#48]
When calling Localization.EnsureInitialized() while the `_System\Publish Settings` page of that publication is not published should not throw an `DxaItemNotFoundException`.

The Localization objects of not-publised sites can appear in the Localization.SiteLocalizations of other publications. Hence it is not unexpected if the `_System\Publish Settings` is not available and Localization should not throw an exception.

Maybe when the `_System\Publish Settings` page is not published this publication should not be listed in the `Localization.SiteLocalizations` at all.

**Comment by rpannekoek** [comment]
I would expect the `Localization.EnsureInitialized` method to throw an exception when the Localization cannot be initialized (because the underlying Publication is not published); I don't like silently ignoring error conditions (it tends to lead to unclear errors/exception later in the process).
However, it seems to me this "issue" is related to your work-around for another issue: https://github.com/sdl/dxa-web-application-dotnet/issues/45
Do you think this issue is still relevant if that other issue would be fixed?

**Comment by jhorsman** [comment]
This issue is releated to #45 in the sense that #45 has a try-catch block as a workaround for this exception. 

Comment https://github.com/sdl/dxa-web-application-dotnet/issues/45#issuecomment-286169679 is descibing a workaournd to load all localizations. It calls `Localization.EnsureInitialized()` which might throw this exception.

This issue (#48) will still be relevant when #45 is resolved because there can be other logic which calls `Localization.EnsureInitialized()`.

**Comment by jhorsman** [comment]
Maybe the real issue is that the Localization object exists in the first place. I agree that something should happen when `Localization.EnsureInitialized()' cannot load the Localization, but it is is unexpected when a publication's settings page is not published?

If DXA would load all `Localization.SiteLocalizations` and remove the SiteLocalizations which cannot be loaded then it would not be an issue, and Localization.EnsureInitialized() can thow the error indeed.

**Comment by rpannekoek** [comment]
I agree with the idea to suppress Localization for Publications which are not published from `Localization.SiteLocalizations`  and still letting `Localization.EnsureInitialized` throw an exception in case it cannot be initialized (this is really be an exceptional, unrecoverable error condition).  Would you agree with closing this issue and keeping #48 open, then?

**Comment by jhorsman** [comment]
yes, agree 👍
