### ISSUE TITLE
Issues with Nuget package

### ISSUE THREAD

**Issue by ariugwu** [sdl/dxa-web-application-dotnet#49]
When you pull in the DXA framework via Nuget:

* 1.7 appears broken. The Common library seems to be missing the Context Service Claims Provider

Am I missing something?

**Comment by rpannekoek** [comment]
Please elaborate on the problem you're observing. And please post questions on http://tridion.stackexchange.com

**Comment by ariugwu** [comment]
Not really a question.

Upgrade the DXA Framework package from 1.6 to 1.7
ContextServiceClaimsProvider cannot be found when referenced in the Unity Config.
The Interface appears to be missing in Sdl.Web.Common.Interfaces.

I've reverted back to 1.6 for the time being.

**Comment by rpannekoek** [comment]
The interface not missing. See https://github.com/sdl/dxa-web-application-dotnet/blob/release/1.7/Sdl.Web.Common/Interfaces/IContextClaimsProvider.cs
What is the exact error you are getting?

**Comment by rpannekoek** [comment]
Reported issue in unclear / not reproducible.
