### ISSUE TITLE
Views declaration could be automated in AreaRegistration classes

### ISSUE THREAD

**Issue by PhilConil** [sdl/dxa-web-application-dotnet#5]
•	Could views be programmatically/automatically declared in each AreaRegistration class? 
•	Example:
RegisterViewModel("Footer", typeof(RegionModel), "Region");
Becomes
RegisterViewModel(viewname, typeof(modelfoundinviewfile), foldername); 
•	The folder hierarchy gives you the ControllerName parameter (only needed for views inside Navigation, Page and Region folders)
•	You may need to parse the views the get the corresponding Model to pass as param, or do some magic.
•	This could possibly allow the creation of “hot” views / views created on the fly, without recompiling would be awesome!

**Comment by rpannekoek** [comment]
If you don’t override RegisterAllViews in your AreaRegistration, it will read all Views from disk, compile them and infer the View Model Type from them.
This does make application startup slower and hence the possibility to explicitly register Views has been introduced in DXA 1.1.

**Comment by rpannekoek** [comment]
Feature already exists (for .NET), but is not recommended for performance reasons.
