### ISSUE TITLE
Log4Net dependency is shipped as assembly in the DXA package

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#50]
The DXA Framework NuGet package contains the assembly for Log4net 2.0.3 and the target file forces the using web application to use this specific version. Log4net should be a NuGet dependency instead.

A practical use case is [Application Insights](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Log4NetAppender/) which requires Log4net 2.0.5 or higher. Currently you cannot upgrade Log4Net since the DXA Framework adds Log4net 2.0.3 to the build output of your DXA site.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12794

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
