### ISSUE TITLE
DXA 2.0 CTP - if using auto-registration for CIS content service, DXA Model Service registration is lost after restart

### ISSUE THREAD

**Issue by NunoLinhares** [sdl/dxa-web-application-dotnet#53]
DXA 2.0 Model service registers its information as extension properties in the content service. If the content service is using auto-registration, this information is lost after a server restart.

A work-around/solution for this is to **not** use auto-registration for the content service, and instead add this to the discovery service's cd_storage_conf.xml:

`<Role Name="ContentServiceCapability" Url="http://your-machine:8081/content.svc">
    <Property Name="dxa-model-service" Value="your-machine:8998"/>
</Role>`

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12634

Note that this is an issue in UDP/DXD, so requires a UDP release to get fixed.

**Comment by rpannekoek** [comment]
The issue has been fixed in DXD 11.0 (part of Sites 9.0).
