### ISSUE TITLE
WebRequestContext.CalculateScreenWidth() should default to 1024px / ScreenWitdh.Medium

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#54]
I have ran into an edge case where the WebRequestContext.ScreenWidth becomes `ExtraSmall` while it is in fact a desktop.

This following piece of code in Sdl.Web.Mvc\Configuration\WebRequestContext.cs checks is the cookie is present and if it is assumes the contextengine provides a DisplayWidth. When ContextEngine is not pupulated (i.e. not wired up to the Context Service) the width is 0 and `CalculateScreenWidth()` returns `Extra Small`.

        protected static ScreenWidth CalculateScreenWidth()
        {
            int width = IsContextCookiePresent ? ContextEngine.GetClaims<BrowserClaims>().DisplayWidth : 1024;
            if (width < SiteConfiguration.MediaHelper.SmallScreenBreakpoint)
            {
                return ScreenWidth.ExtraSmall;
            }
            if (width < SiteConfiguration.MediaHelper.MediumScreenBreakpoint)

To correct the situtation the code should check if the DisplayWith is bigger than 0.

**Comment by majiccode** [comment]
internal issue created: https://jira.sdl.com/browse/TSI-2894

**Comment by rpannekoek** [comment]
Fixed in DXA 1.8 and 2.0
