### ISSUE TITLE
Sdl.Web.Common.Models.PageModel.GetXpmMarkup() calls unused XpmMetadata

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#59]
[`Sdl.Web.Common.Models.PageModel.GetXpmMarkup()`](https://github.com/sdl/dxa-web-application-dotnet/blob/master/Sdl.Web.Common/Models/PageModel.cs) tries to retrieve the "CmsUrl" from the XpmMetadata. When this fails it will use the core.cmsurl config value from the Localization

            if (XpmMetadata.TryGetValue("CmsUrl", out cmsUrlValue))
            {
                cmsUrl = (string) cmsUrlValue;
            }
            else
            {
                cmsUrl = localization.GetConfigValue("core.cmsurl");
            }

The CmsUrl in the XpmMetadata is never used. We get the CMS URL from the web.config or from the Topology Manager.

Also, I think it is not logical to try to get the system wide CMS URL from the XpmMetadata. The latter has the page scope and we cannot have a different CMS URL for each page.

So I think we can safely remove the `if (XpmMetadata.TryGetValue("CmsUrl", out cmsUrlValue))`.

**Comment by majiccode** [comment]
Created internal issue: https://jira.sdl.com/browse/TSI-2899

**Comment by rpannekoek** [comment]
Fixed in DXA 1.8 and 2.0
