### ISSUE TITLE
Includes Pages don't allow for custom area

### ISSUE THREAD

**Issue by JaimeSA** [sdl/dxa-web-application-dotnet#6]
When converting includes into regions, the system assumes they always are in the "Core" (Default) area. The system should allow to specify the area to look for the included page (Page Template Metadata for MVC in the same way is done for other page templates). If not provided, then inherit it from the MVC data of the page doing the include, i.e. the including page area.

The method in question is in the DefaultModelBuilder class and it is called: `GetRegionFromIncludePage(IPage page)`.

As a temporary solution, I have added an optional parameter: `MvcData parentMvc`:

        private static RegionModel GetRegionFromIncludePage(IPage page, MvcData parentMvc)
        {
            string regionName = page.Title;

            MvcData regionMvcData = new MvcData(regionName);
            if (parentMvc != null)
            {
                regionMvcData.AreaName = parentMvc.AreaName;
            }
            InitializeRegionMvcData(regionMvcData);

            return new RegionModel(regionName)
            {
                MvcData = regionMvcData,
                XpmMetadata = new Dictionary<string, string>
                {
                    {RegionModel.IncludedFromPageIdXpmMetadataKey, page.Id},
                    {RegionModel.IncludedFromPageTitleXpmMetadataKey, page.Title},
                    {RegionModel.IncludedFromPageFileNameXpmMetadataKey, page.Filename}
                }
            };
        }

And I pass by, the mvcdata from the including page as follows:

`RegionModel includePageRegion = GetRegionFromIncludePage(includePage, pageModel.MvcData);`

**Comment by jsuurd** [comment]
Hi Bart,

Is this issues supposed to be resolved? I still have the same issue, and I have to apply Jaime's workaround to make it work. (working on commit cf587fc)

**Comment by rpannekoek** [comment]
Hi Jeroen.  This is indeed resolved in DXA 1.2.  The trick it that the Title of the include Page can be a qualified name. That is:  `<Module/AreaName>:<Region(View)Name>`  For example:  `MyArea:Header`
