### ISSUE TITLE
DXA1.6 web solution (dxa-web-application-dotnet-DXA_1.6_Release.zip)

### ISSUE THREAD

**Issue by btruong806** [sdl/dxa-web-application-dotnet#60]
Hello DXA Team,
It appears the DXA1.6 web solution (dxa-web-application-dotnet-DXA_1.6_Release.zip) is made to work with Web 8.x as the web.config in the solution has reference to Discovery service. 

However, as I understand correctly, DXA 1.6 is compatible for Tridion 2013sp1hr1 and Discovery service is only applicable for SDL Web 8.x.....
Given the above, is there a DXA 1.6 web solution that is made for Tridion 2013sp1 ?

I see from this URL:
https://github.com/sdl/dxa-web-application-dotnet/releases?after=DXA_1.7_Sprint_2
where Rick mentioned these are the highlights in DXA 1.6
On-demand, Taxonomy-based navigation
    Clearly separated Core Module
    Support for HTML forms
    Caching of DXA View Models
    Upgrade to CIL 8.3

so indeed DXA 1.6 was upgraded to CIL 8.3, so this web solution will not work for Tridion 2013sp1hr1 as I assume for Tridion 2013sp1hr1, it does not know how to handle the new microservice framework.

Please advise on the next step...

I also asked this in jira (SRQ-7461)

**Comment by rpannekoek** [comment]
This is not an Issue, but a Question. Please use Tridion Stack Exchange for those.
DXA 1.6 support both SDL Web 8 and SDL Tridion 2013 SP1. See the DXA docs, for example: http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v6/GUID-EAD26E50-9ABE-47EA-95B0-F556106F5E3C
