### ISSUE TITLE
Language selector URL does not expect null page id

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#61]
The `Resolve` action in the `PageController` cannot handle a null or empty page id in the `itemId` parameter. It should be more flexible and accept if no page id is passed.

The current behavior when page id 0 is passed is acceptable. In that case the controller redirects to the default page of the site.

For example this URL `http://localhost/resolve/82?localizationId=51&defaultPath=/demo/` will work fine. It will try to resolve page id 82 in publication 51.

When the request does not have the context of a page this URL with page id 0 can be used `http://localhost/resolve/0?localizationId=51&defaultPath=/demo/`.

However if no page id is passed like `http://localhost/resolve/?localizationId=51&defaultPath=/demo/` the webapplication returns an unexpected error:

	Server Error in '/' Application.

	Unexpected item type in TCM URI: tcm:0-0-0

	Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

	Exception Details: Sdl.Web.Common.DxaException: Unexpected item type in TCM URI: tcm:0-0-0

	Source Error: 

	An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by majiccode** [comment]
Internal issue created: https://jira.sdl.com/browse/TSI-2898

**Comment by rpannekoek** [comment]
Fixed in DXA 1.8 and 2.0
