### ISSUE TITLE
Have DXA sources in a symbol server 

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#64]
I would like to be able to step though the DXA source code in Visual Studio. During web application development ReSharper and DotPeek can decompile the DXA assemblies, but it would be much nicer if the DXA pdbs are available on a publically available symbol server.

Also with the pdbs available we can step though the DXA source code and inspect how DXA works, and enhance troubleshooting.

**Comment by majiccode** [comment]
internal issue for tracking purposes : TSI-1466

currently this is implemented but has not been used or tested just yet. Hopefully the impending release of DXA 2.0 we will finally see symbols uploaded to nuget symbol server

**Comment by rpannekoek** [comment]
Symbols are published to NuGet.org for DXA 2.1 (and higher).
