### ISSUE TITLE
Only possible to embedded MediaItem entities in Rich Text fragments

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-dotnet#65]
The ability to embed entities in Rich Text fragments is great, and can simply be made more generic to allow more than just images. 

See sdl/dxa-content-management#13 for the corresponding issue to change the publishing process

See https://github.com/sdl/dxa-web-application-java/issues/93 for the corresponding issue for the Java web app

**Comment by rpannekoek** [comment]
Internal ID (for tracking purposes): CRQ-12781

**Comment by rpannekoek** [comment]
Incorporated in DXA 2.2.
