### ISSUE TITLE
Component Link mapping fails after link depth reached in web application.

### ISSUE THREAD

**Issue by stanlk** [sdl/dxa-web-application-dotnet#67]
In CM we have expandLinkDepth  parameter, that will limit how many level of linked components are added to JSON. 

However in web app DXA 2.0 during model mapping it fails, when link depth limit is reached in json. Error message:
`Unable to map field 'SimilarBooks' to property Book.SimilarBooks of type ...`

It fails on this line of BuildEntityModel method of DefaultModelBuilder, because SchemaId is null.
`SemanticSchema semanticSchema = SemanticMapping.GetSchema(entityModelData.SchemaId, localization);`

More details [here](https://tridion.stackexchange.com/questions/18977/how-to-handle-component-link-circular-reference-in-dxa-2-0)

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12790

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
