### ISSUE TITLE
Multiple html designs cannot be published at the same time if they have files with the same filename.

### ISSUE THREAD

**Issue by JaimeSA** [sdl/dxa-web-application-dotnet#7]
We created two Modules with different html design elements (css, js, etc...). They both have a file called style.css (pretty common) but they get published to different structure groups /system/assets/design1 and /system/assets/design2, however the Template that processes the Modules assings the variantId using this pattern: dist-filename, now since the html design is published using the same component (Same binary id) when you have this situation, you encounter that the same variant Id is going to be used and that's not allowed.

I've implemented a workaround that adds the structure group id to the variant id:

dist-sgId-filename, that way you can publish files with the same filename in different html designs on your modules.

**Comment by rpannekoek** [comment]
TSI-1303 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.6.
