### ISSUE TITLE
ModelServiceClient ArgumentNullException crash

### ISSUE THREAD

**Issue by ronnqvistandreas** [sdl/dxa-web-application-dotnet#70]
ModelServiceClient throws an ArgumentNullException when it times out in PerformRequest method.

Reproducable by setting timeout for model service to 1ms. 

What happens is a ModelServiceException is thrown on line 214, which is captured in the general catch block on line 118. This sets the **success** flag to false, but does not set **responseBody**. This leads to null being passed into JsonConvert.DeserializeObject on line 135. This leads to the original timeout exception being lost and instead a ArgumentNullException is thrown.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12789

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
