### ISSUE TITLE
HtmlHelper null pointer exceptions

### ISSUE THREAD

**Issue by jhorsman** [sdl/dxa-web-application-dotnet#74]
The `HtmlHelperExtensions` can throw null pointer exceptions when certain variables like `htmlHelper.ViewData[DxaViewDataItems.ContainerSize]` are not set.

While this data should normally be set, the `HmlHelper` should not throw a null pointer exception when this data is not available in the ViewData. 

Seen in DXA 2.1

**Comment by jhorsman** [comment]
One of the occurrences is fixed in #73. There are more similar instances.

**Comment by rpannekoek** [comment]
Internal issue ID (for tracking purposes): CRQ-14323

**Comment by rpannekoek** [comment]
Fixed in DXA 2.2
