### ISSUE TITLE
Expose page metadata in inner regions (at least in the "included" pages)

### ISSUE THREAD

**Issue by JaimeSA** [sdl/dxa-web-application-dotnet#8]
Use case:
Let's say that the "header" has 5 features:
- logo
- navigation
- login link
- call us link
- shopping cart

I need a way (Ideally page metadata) to turn on/off those features, however, the "Header" region (a include) doesn't know anything about page metadata

**Comment by rpannekoek** [comment]
TSI-1947 (internal issue ID for tracking purposes)

**Comment by rpannekoek** [comment]
Fixed in DXA 1.6: Region View and Entity View can access the Page Model through WebRequestContext.PageModel (also applies to DXA Java).
